dist: trusty
language: c++
sudo: false

script:
  - "autoreconf -f && mkdir -p build-out && cd build-out && ../configure --enable-optimize && make"

branches:
  only:
    - master

compiler:
  - clang
  - gcc-5

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-5
        - g++-5
        - gcc-5-multilib
        - g++-5-multilib
        - clang
        - automake
        - autoconf

notifications:
    email:
        - doug16k@gmail.com

after_success:
    - cd build-out && ls
