dist: trusty
language: c++
sudo: false

script:
  - "mkdir -p build-out && ../configure --enable-optimize && make"

branches:
  only:
	- master

env:
  matrix:
	- CC=gcc-5 CXX=g++-5
	- CC=clang CXX=clang++

addons:
  apt:
	sources:
		- ubuntu-toolchain-r-test
	packages:
		- gcc-5
		- g++-5
		- gcc-5-multilib
		- g++-5-multilib
		- clang-4.0

notifications:
	email:
		- doug16k@gmail.com

after_success:
	- cd build-out && ls
